name: Build BitWiper EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --add-data "event.gif:." --add-data "Spark.png:." BitWiper.py
          ls -R dist

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: BitWiper-EXE
          path: dist/BitWiper*
